version: '3.9'

services:
  backend:
    build:
      context: ./backend
      args:
        - HOST=0.0.0.0
        - PORT=4000
    expose:
      - 4000
    env_file:
      - env/.env-prod-backend
    networks:
      - portfolio-network

  frontend:
    build:
      context: ./frontend
      args:
        - HOST=0.0.0.0
        - PORT=4000
    expose:
      - 4000
    env_file:
      - env/.env-prod-frontend
    depends_on:
      - backend
    networks:
      - portfolio-network

  nginx:
    image: nginx:latest
    # container_name: portfolio-nginx
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/certbot/www/:/var/www/certbot/:ro
      # - ./nginx/certbot/conf:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-network

  certbot:
    image: certbot/certbot
  #   container_name: certbot
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf:/etc/letsencrypt
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
