version: '3.9'

services:

  # Hot-reload
  backend:
    container_name: portfolio-backend
    build:
      context: ./backend
      args:
        - HOST=0.0.0.0
        - PORT=4000
    ports:
      - 4001:4000
    volumes:
      - ./backend/app:/app
      - ./backend/requirements.txt:/app/requirements.txt
      - ./backend/script.sh:/app/script.sh
    env_file:
      - env/.env-dev-backend
    networks:
      - portfolio-network

  # Not hot-reload
  frontend:
    container_name: portfolio-frontend
    build:
      context: ./frontend
      args:
        - HOST=0.0.0.0
        - PORT=4000
    ports:
      - 4000:4000
    env_file:
      - env/.env-dev-frontend
    networks:
      - portfolio-network

  nginx:
    image: nginx:latest
    # container_name: portfolio-nginx
    volumes:
      - ./nginx/conf/app-dev.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
