test:
	python3 -m pytest --verbose app/tests

test-cov:
	python3 -m pytest --verbose app/tests --cov

test-cov-html:
	python3 -m pytest --verbose app/tests --cov --cov-report=html

norm:
	python3 -m flake8 --ignore=E501 app
